version: '3'
services:
  bdd-postgres:
    image: postgres:13.4
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bdd-sistema-citas-medicas
    volumes:
      - ./docker/data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 8080:80
    volumes:
      - ./docker/pgadmin:/var/lib/pgadmin
    depends_on:
      - bdd-postgres